<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <form action="../controlador/entrada.php" method="post">
    
        <input name="usuario" id="cuadro_1" type="text" placeholder="Usuario" require>

        <input name="contraseña" id="cuadro_2" type="password" placeholder="Contraseña" require>

        <input name="enviar" id="boton" type="submit" value="Enviar">
    
    </form>

    <?php

        require_once($contenido);

    ?>
    
</body>
</html>