<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <link rel="stylesheet" href="../assets/css/style.css">
    <title>Document</title>
</head>
<body>

    <div class="contenedorGneral">

        <div class="contenedorSeleccion">

            <form action="../controlador/entrada.php" method="post">
            
                <input name="usuario" class="entrada" id="cuadro_1" type="text" placeholder="Usuario" require><br><br><br>

                <input name="contraseña" class="entrada" id="cuadro_2" type="password" placeholder="Contraseña" require><br><br><br>

                <input name="enviar" class="BotonIngreso" id="boton" type="submit" value="Enviar">
            
            </form>

        </div>



    </div>



    <?php

        require_once($contenido);

    ?>
    
</body>
</html>