<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../assets/css/style2.css">
    <title>Document</title>
</head>
<body>
    

    <div class="contenedorGneral">

    

        <div class="contenedorSeleccion">

            
            
            <form action="" method="post">
            
                <input type="text" class="entrada" placeholder="Documento" require><br><br><br>

                <select class="entrada" name="" id="">
                
                    <option>Ubicacion</option>
                    <option>ambiente1</option>
                    <option>ambiente2</option>
                    <option>ambiente3</option>
                
                </select><br><br>

                <input type="submit" class="BotonIngreso" value="Enviar">
            
            </form>

            <img class="cuadro2" src="../assets/img/persona.png" alt="">

            <a href="registro.phtml" class="BotonRegistro">Registro</a>

        </div> 
    

    </div>
</body>
</html>