<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../assets/css/style3.css">
    <title>Document</title>
</head>
<body>
    
    <div class="contenedor">

        <a href="tabs/ubicacion.phtml" class="BotonRegistro">Ubicacion</a>
        <a href="tabs/usuarios.phtml" class="BotonRegistro">Usuarios</a>
        <a href="tabs/fichas.phtml" class="BotonRegistro">Ficha</a>
        <a href="tabs/rep_usu.phtml" class="BotonRegistro">Repo_Usuario</a>
        <a href="tabs/rep_ficha.phtml" class="BotonRegistro">Repo_Ficha</a>
        <a href="tabs/rep_ambient.phtml" class="BotonRegistro">Repo_Ambiente</a>

    </div>


</body>
</html>