<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../assets/css/style5.css">
    <title>Document</title>
</head>
<body>

    <div class="contenedor">

        <form action="" method="post">

            <select class="entrada" name="" id="">
                
                <option>Ambiente</option>
                <option>ambiente1</option>
                <option>ambiente2</option>
                <option>ambiente3</option>
            
            </select><br><br>

            <h1>FechaInicio</h1>
            <input class="entrada" type="date"><br><br>

            <h1>FechaFin</h1>
            <input class="entrada" type="date"><br><br>

            <input type="submit" class="BotonIngreso" value="Enviar">

        </form>

    </div>

</body>
</html>